runtime: python312
handlers: 
  # Serve all static files with url ending with a file extension
  - url: /
    static_files: dist/patrik-kubicek/browser/index.html
    upload: dist/patrik-kubicek/browser/index.html
    secure: always
  - url: /
    static_dir: dist/patrik-kubicek/browser
    secure: always
  - url: /(.*)
    static_files: dist/patrik-kubicek/browser/index.html
    upload: dist/patrik-kubicek/browser/index.html
    secure: always