runtime: nodejs18

handlers: 
  # Serve all static files with url ending with a file extension
  - url: /(.*\.html)
    static_files: dist/patrik-kubicek/**/(.*\.html)
    upload: dist/patrik-kubicek/**/(.*\.html)
    secure: always
    
  - url: /(.*\.js)
    static_files: dist/patrik-kubicek/**/(.*\.js)
    upload: dist/patrik-kubicek/**/(.*\.js)
    secure: always
    
  - url: /(.*\.css)
    static_files: dist/patrik-kubicek/**/(.*\.css)
    upload: dist/patrik-kubicek/**/(.*\.css)
    secure: always
    
  - url: /(.*\.ico)
    static_files: dist/patrik-kubicek/**/(.*\.ico)
    upload: dist/patrik-kubicek/**/(.*\.ico)
    secure: always

  # Catch all handler to index.html
  - url: /.*
    static_files: dist/patrik-kubicek/browser/index.html
    upload: dist/patrik-kubicek/browser/index.html
    secure: always