runtime: python312
api_version: 1

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
default_expiration: 60s

handlers:

# To enhance security, all http requests are redirected to their equivalent https addresses (secure: always).

# Assets are retrieved directly from their parent folder.
- url: /assets
  static_dir: dist/patrik-kubicek/assets
  secure: always

# Static files located in the root folder are retrieved directly from there, but their suffixes need to be
# mapped individually in order to avoid them from being hit by the most general (catch-all) rule.
- url: /(.*\.css)
  static_files: dist/patrik-kubicek/\1
  upload: dist/patrik-kubicek/(.*\.css)
  secure: always

- url: /(.*\.html)
  static_files: dist/patrik-kubicek/\1
  upload: dist/patrik-kubicek/(.*\.html)
  secure: always

- url: /(.*\.ico)
  static_files: dist/patrik-kubicek/\1
  upload: dist/patrik-kubicek/(.*\.ico)
  secure: always

- url: /(.*\.js)
  static_files: dist/patrik-kubicek/\1
  upload: dist/patrik-kubicek/(.*\.js)
  secure: always

- url: /(.*\.txt)
  static_files: dist/patrik-kubicek/\1
  upload: dist/patrik-kubicek/(.*\.txt)
  secure: always

# Site root.
- url: /
  static_files: dist/patrik-kubicek/index.html
  upload: dist/patrik-kubicek/index.html
  secure: always

# Catch-all rule, responsible from handling Angular application routes (deeplinks).
- url: /.*
  static_files: dist/patrik-kubicek/index.html
  upload: dist/patrik-kubicek/index.html
  secure: always