steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: [ run, build, --prod ]
 
  - name: gcr.io/cloud-builders/gcloud
    args: [ app, deploy ]